language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
env:
  # - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
# matrix:
#   allow_failures:
#     - env: MRUBY_VERSION=master
branches:
  only:
    - master

script:
  - rake test
